all:
	g++ PyAFM.cpp -shared -fPIC -I /usr/include/python3.6m/ -I /usr/include/boost/ -L /usr/lib/x86_64-linux-gnu/ -L /usr/lib/python3.6/config-3.6m-x86_64-linux-gnu/ -lpython3.6m -lboost_python36 -lboost_numpy36 -o PyAFM.so
